#!/bin/bash
# JackMediaMan Installer
# Usage: curl -sSL https://raw.githubusercontent.com/jackneil/jackmediaman/main/install.sh | bash
#
# This script:
#   1. Detects best available virtual environment tool (uv, conda, venv)
#   2. Creates an isolated virtual environment for JackMediaMan
#   3. Installs JackMediaMan and all dependencies
#   4. Sets up system-wide 'jmm' command (wrapper script + shell alias)
#   5. Runs auto-setup (discovers Plex, configures Deluge)

set -e

# Configuration
INSTALL_DIR="${JMM_INSTALL_DIR:-$HOME/.jackmediaman}"
VENV_DIR="$INSTALL_DIR/venv"
BIN_DIR="$HOME/bin"

echo "=========================================="
echo "  JackMediaMan Installer"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Detected venv tool
VENV_TOOL=""
CONDA_CMD=""

# Check for Python 3.10+
check_python() {
    if ! command -v python3 &> /dev/null; then
        echo -e "${RED}Error: Python 3 is required${NC}"
        echo "Install Python 3.10+ and try again"
        exit 1
    fi

    # Check version
    PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
    MAJOR=$(echo $PYTHON_VERSION | cut -d. -f1)
    MINOR=$(echo $PYTHON_VERSION | cut -d. -f2)

    if [ "$MAJOR" -lt 3 ] || ([ "$MAJOR" -eq 3 ] && [ "$MINOR" -lt 10 ]); then
        echo -e "${RED}Error: Python 3.10+ required (found $PYTHON_VERSION)${NC}"
        exit 1
    fi

    echo -e "${GREEN}✓ Found Python $PYTHON_VERSION${NC}"
}

# Detect best available virtual environment tool
detect_venv_tool() {
    echo ""
    echo "Detecting virtual environment tools..."

    # Priority 1: uv (modern, fast)
    if command -v uv &> /dev/null; then
        VENV_TOOL="uv"
        echo -e "${GREEN}✓ Found uv (recommended)${NC}"
        return
    fi

    # Priority 2: conda/miniconda/mamba
    if command -v mamba &> /dev/null; then
        VENV_TOOL="conda"
        CONDA_CMD="mamba"
        echo -e "${GREEN}✓ Found mamba${NC}"
        return
    fi

    if command -v conda &> /dev/null; then
        VENV_TOOL="conda"
        CONDA_CMD="conda"
        echo -e "${GREEN}✓ Found conda${NC}"
        return
    fi

    # Priority 3: venv (fallback, always available with Python 3)
    if python3 -c "import venv" &> /dev/null; then
        VENV_TOOL="venv"
        echo -e "${GREEN}✓ Using built-in venv${NC}"
        return
    fi

    echo -e "${RED}Error: No virtual environment tool found${NC}"
    echo "Please install one of: uv, conda, or ensure Python venv module is available"
    exit 1
}

# Create virtual environment
create_venv() {
    echo ""
    echo "Creating virtual environment at $VENV_DIR..."

    # Create install directory
    mkdir -p "$INSTALL_DIR"

    # Remove existing venv if present
    if [ -d "$VENV_DIR" ]; then
        echo -e "${YELLOW}Removing existing virtual environment...${NC}"
        rm -rf "$VENV_DIR"
    fi

    case "$VENV_TOOL" in
        uv)
            echo -e "${BLUE}Using uv to create venv...${NC}"
            uv venv "$VENV_DIR" --python python3
            ;;
        conda)
            echo -e "${BLUE}Using $CONDA_CMD to create environment...${NC}"
            # For conda, we create a named environment in the install dir
            $CONDA_CMD create -y -p "$VENV_DIR" python=3.10
            ;;
        venv)
            echo -e "${BLUE}Using venv to create environment...${NC}"
            python3 -m venv "$VENV_DIR"
            ;;
    esac

    echo -e "${GREEN}✓ Virtual environment created${NC}"
}

# Install JackMediaMan into the virtual environment
install_package() {
    echo ""
    echo "Installing JackMediaMan..."

    case "$VENV_TOOL" in
        uv)
            # uv can install directly into a venv
            uv pip install --python "$VENV_DIR/bin/python" "jackmediaman[web]"
            ;;
        conda)
            # Activate conda env and install via pip
            source "$VENV_DIR/bin/activate" 2>/dev/null || source activate "$VENV_DIR"
            pip install "jackmediaman[web]"
            ;;
        venv)
            # Activate venv and install
            source "$VENV_DIR/bin/activate"
            pip install --upgrade pip
            pip install "jackmediaman[web]"
            ;;
    esac

    echo -e "${GREEN}✓ JackMediaMan installed${NC}"
}

# Set up system-wide jmm command
setup_command() {
    echo ""
    echo "Setting up system-wide 'jmm' command..."

    # Create bin directory if needed
    mkdir -p "$BIN_DIR"

    # Create wrapper script
    cat > "$BIN_DIR/jmm" << EOF
#!/bin/bash
# JackMediaMan wrapper - auto-generated by install.sh
exec "$VENV_DIR/bin/jmm" "\$@"
EOF
    chmod +x "$BIN_DIR/jmm"
    echo -e "${GREEN}✓ Created $BIN_DIR/jmm${NC}"

    # Detect shell and rc file
    SHELL_NAME=$(basename "$SHELL")
    case "$SHELL_NAME" in
        bash) RC_FILE="$HOME/.bashrc" ;;
        zsh)  RC_FILE="$HOME/.zshrc" ;;
        fish) RC_FILE="$HOME/.config/fish/config.fish" ;;
        *)    RC_FILE="$HOME/.bashrc" ;;
    esac

    # Add ~/bin to PATH if not already there
    if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
        if [ -f "$RC_FILE" ] && ! grep -q "$BIN_DIR" "$RC_FILE"; then
            echo "" >> "$RC_FILE"
            echo "# JackMediaMan" >> "$RC_FILE"
            if [ "$SHELL_NAME" = "fish" ]; then
                echo "set -gx PATH \"$BIN_DIR\" \$PATH" >> "$RC_FILE"
            else
                echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$RC_FILE"
            fi
            echo -e "${GREEN}✓ Added $BIN_DIR to PATH in $RC_FILE${NC}"
        fi
    fi

    # Add shell aliases (these take precedence in interactive shells)
    if [ -f "$RC_FILE" ]; then
        # Remove old alias if exists
        if grep -q "alias jmm=" "$RC_FILE"; then
            # Update existing alias
            if [ "$(uname)" = "Darwin" ]; then
                sed -i '' "s|alias jmm=.*|alias jmm='$VENV_DIR/bin/jmm'|" "$RC_FILE"
            else
                sed -i "s|alias jmm=.*|alias jmm='$VENV_DIR/bin/jmm'|" "$RC_FILE"
            fi
            echo -e "${GREEN}✓ Updated jmm alias in $RC_FILE${NC}"
        else
            # Add new alias
            echo "" >> "$RC_FILE"
            echo "# JackMediaMan aliases" >> "$RC_FILE"
            if [ "$SHELL_NAME" = "fish" ]; then
                echo "alias jmm='$VENV_DIR/bin/jmm'" >> "$RC_FILE"
                echo "alias jackmediaman='$VENV_DIR/bin/jmm'" >> "$RC_FILE"
            else
                echo "alias jmm='$VENV_DIR/bin/jmm'" >> "$RC_FILE"
                echo "alias jackmediaman='$VENV_DIR/bin/jmm'" >> "$RC_FILE"
            fi
            echo -e "${GREEN}✓ Added jmm alias to $RC_FILE${NC}"
        fi
    fi

    # Export PATH for current session
    export PATH="$BIN_DIR:$PATH"
}

# Run auto-setup
run_setup() {
    echo ""
    echo "Running auto-setup..."
    echo ""

    JMM_CMD="$VENV_DIR/bin/jmm"

    if [ -x "$JMM_CMD" ]; then
        # Run setup init with auto-discovery
        $JMM_CMD setup init --force || true
    else
        echo -e "${YELLOW}Warning: jmm command not found at $JMM_CMD${NC}"
    fi
}

# Show installation info
show_info() {
    echo ""
    echo "=========================================="
    echo -e "${GREEN}  Installation complete!${NC}"
    echo "=========================================="
    echo ""
    echo "Installation details:"
    echo "  Virtual env tool: $VENV_TOOL"
    echo "  Install location: $INSTALL_DIR"
    echo "  Command wrapper:  $BIN_DIR/jmm"
    echo ""
    echo "To get started:"
    echo "  jmm               - Show configuration status"
    echo "  jmm process PATH  - Process a torrent/media file"
    echo "  jmm --web         - Launch web interface"
    echo "  jmm --help        - Show all commands"
    echo ""
    echo -e "${YELLOW}NOTE: Restart your terminal or run:${NC}"
    echo "  source $RC_FILE"
    echo ""
}

# Uninstall function (can be called with --uninstall)
uninstall() {
    echo "Uninstalling JackMediaMan..."

    # Remove install directory
    if [ -d "$INSTALL_DIR" ]; then
        rm -rf "$INSTALL_DIR"
        echo -e "${GREEN}✓ Removed $INSTALL_DIR${NC}"
    fi

    # Remove wrapper script
    if [ -f "$BIN_DIR/jmm" ]; then
        rm -f "$BIN_DIR/jmm"
        echo -e "${GREEN}✓ Removed $BIN_DIR/jmm${NC}"
    fi

    echo ""
    echo "JackMediaMan has been uninstalled."
    echo "You may want to manually remove aliases from your shell rc file."
}

# Main
main() {
    # Check for uninstall flag
    if [ "$1" = "--uninstall" ] || [ "$1" = "-u" ]; then
        uninstall
        exit 0
    fi

    check_python
    detect_venv_tool
    create_venv
    install_package
    setup_command
    run_setup
    show_info
}

main "$@"
